# Generated by Django 6.0.2 on 2026-02-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newappmodel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
